apps/usuario/urls.py
from django.urls import path

#Perfil Usuario Login
from apps.usuario.view.views_perfil import LoginPerfilView,DashboardView,LogoutView,UsuarioPerfilDetalleView,UsuarioPerfilEditarView,passwordusuarioview

#Usuario
from apps.usuario.view.views_usuario import UsuarioListarView,UsuarioCrearView,UsuarioEditaView,UsuarioDetallesView,\
    UsuarioEliminarView,usuariodesactivar,usuarioactivar,cambiar_estado_usuario

#Perfil
from apps.usuario.view.views_perfil import PerfilListarView

app_name = 'usuario'
#int uuid
urlpatterns = [
    # Login
    path('', LoginPerfilView.as_view(), name='index'),
    path('logout/', LogoutView, name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    #Configuracion
    path('perfil/<slug:usuario_url>/usuario/', UsuarioPerfilDetalleView.as_view(), name='perfil_usuario'),
    path('perfil/usuario', UsuarioPerfilEditarView.as_view(), name='perfil_actualizar'),
    path('perfil/password/', passwordusuarioview, name='cambiar_password'),

    #Usuario
    path('listar/usuario/', UsuarioListarView.as_view(), name='listar_usuario'),
    path('crear/usuario/', UsuarioCrearView.as_view(), name='crear_usuario'),
    path('editar/<int:pk>/usuario/', UsuarioEditaView.as_view(), name='editar_usuario'),
    path('detalle/<int:pk>/usuario/', UsuarioDetallesView.as_view(), name='detalle_usuario'),
    path('eliminar/<int:pk>/usuario/', UsuarioEliminarView.as_view(), name='eliminar_usuario'),
    #
    path('desactivar/<int:id>/usuario/', usuariodesactivar, name='desactivar_usuario'),
    path('activar/<int:id>/usuario/', usuarioactivar, name='activar_usuario'),
    ##rapido
    path('estado/<int:pk>/usuario/', cambiar_estado_usuario, name='estado_usuario'),
    #

    # Perfil
    path('listar/perfil/', PerfilListarView.as_view(), name='listar_perfil'),
    path('crear/perfil/', UsuarioCrearView.as_view(), name='crear_perfil'),
    path('editar/<int:pk>/perfil/', UsuarioEditaView.as_view(), name='editar_perfil'),
    path('detalle/<int:pk>/perfil/', UsuarioDetallesView.as_view(), name='detalle_perfil'),
    path('eliminar/<int:pk>/perfil/', UsuarioEliminarView.as_view(), name='eliminar_perfil'),
    #
    path('desactivar/<int:id>/perfil/', usuariodesactivar, name='desactivar_perfil'),
    path('activar/<int:id>/perfil/', usuarioactivar, name='activar_perfil'),
    ##rapido
    path('estado/<int:pk>/perfil/', cambiar_estado_usuario, name='estado_perfil'),
    #


]

proyectosigetebr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from apps.usuario import urls as usuario_urls, api_urls as usuario_api_urls


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(usuario_urls, namespace="usuario")),
    #Api Star
    path('api/',include(usuario_api_urls)),
    #Api Exit

    # Contratos
    path('contrato/', include('apps.contrato.urls', namespace="contrato")),

    # Terreno
    path('terreno/', include('apps.terreno.urls', namespace="terreno")),

]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,
                                       document_root=settings.MEDIA_ROOT)

apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin#, User
from django.utils import timezone
from apps.usuario.templatetags.utils import ROLES
import time
import uuid

class UserManager(BaseUserManager):
    def create_user(self, usuario, email, password):
        if not email:
            raise ValueError('El Email o Correo Electronico  es obligatorio')
        user = self.model(email=self.normalize_email(email))
        user.usuario = usuario
        user.set_password(password)
        user.is_staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, usuario, email, password):
        user = self.create_user(usuario, email, password)
        user.is_active = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

def img_url(self, filename):
    hash_ = int(time.time())
    return "%s/%s/%s" % ("media", hash_, filename)

class EstadoModel(models.Model):
    #id = models.UUIDField('id', default=uuid.uuid4, primary_key=True, unique=True, null=False, blank=False,editable=False)
    descripcion = models.TextField('descripcion', blank=True, null=True)
    direccion_ip = models.GenericIPAddressField(blank=True, null=True)
    creacion = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modificacion = models.DateTimeField(auto_now=True, blank=True, null=True)
    estado = models.BooleanField(default=True)
    #uc = models.CharField(max_length=100, blank=True,null=True)
    #uc = models.ForeignKey(Usuario,blank=True,null=True,on_delete=models.CASCADE)#usuario creo
    uc = models.IntegerField(blank=True, null=True)
    #um =models.ForeignKey(User,on_delete=models.CASCADE)#usuario modifico
    #um = models.CharField(max_length=100, blank=True,null=True)
    um = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract = True

class Usuario(AbstractBaseUser, PermissionsMixin):
    #id = models.UUIDField('id', default=uuid.uuid4, primary_key=True, unique=True, null=False, blank=False,editable=False)
    usuario = models.CharField('Usuario', max_length=15, unique=True)
    email = models.EmailField('Correo Electronico',max_length=50,unique=True)
    observacion = models.TextField(blank=True,null=True)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = UserManager()

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'usuario'
    REQUIRED_FIELDS = ['email',]

    def get_short_name(self):
        return self.usuario

    def get_full_name(self):
        return (self.usuario)

    def has_perm(self, perm, obj=None):
        "¿El usuario cuenta con los permisos en especificos?"
        return True

    def has_module_perms(self, app_label):
        "¿El usuario cuenta con los permisos para ver una app en especificos?"
        return True

    def __unicode__(self):
        return "%s" % (self.usuario)
#        return "%s %s" % (self.usuario, self.apellido)

    def __str__(self):
        return "%s" % (self.usuario)
#        return "%s %s" % (self.usuario, self.apellido)

    class Meta:
        ordering = ['-is_active']
        verbose_name_plural = "Usuarios"

#Perfil sera el Login Usuario SIGETEBR
class Perfil(Usuario):
    roles = models.CharField(max_length=20, choices=ROLES, default='Usuario')
    nombre = models.CharField('Nombres', max_length=50)
    apellido = models.CharField('Apellidos', max_length=50)
    phone = models.IntegerField(null=True,blank=True,help_text='Teléfono de contacto')
    perfil_img = models.ImageField(verbose_name='Imagen de Perfil',upload_to=img_url, blank=True, null=True)

    direccion_ip = models.GenericIPAddressField(blank=True, null=True)
    estado = models.BooleanField(default=True) #uc = models.ForeignKey(Usuario,on_delete=models.CASCADE)#usuario creo
    modificacion = models.DateTimeField(auto_now=True)  # , blank=True, null=True)
    uc = models.IntegerField(blank=True,null=True)
    um = models.IntegerField(blank=True,null=True)


    def __str__(self):
        return '%s' % (self.usuario)

    class Meta:
        verbose_name_plural = "Perfiles"

templates/sigetebr/apps/usuario/usuario/include/usuario.html
{% for usuario in list_usuario %}
    <tr class="h6">
        <td> {{ forloop.counter}} </td>

        <td>{{ usuario.usuario }}</td>

        <td>
            {{ usuario.perfil.nombre|default_if_none:"" }} {{ usuario.perfil.apellido|default_if_none:"" }}
        </td>

        <td>{{ usuario.email }}</td>

        {% if usuario.is_active == True %}
        <td class="text-center">
            <span class="right badge badge-success">Activo</span>
        </td>
        {% else %}
            <td class="text-center">
                <span class="right badge badge-danger">Inactivo</span>
            </td>
        {% endif %}

        <td class="text-center">

            <div class="btn-group">
                <button type="button" class="btn btn-info dropdown-toggle btn-sm" data-toggle="dropdown" aria-expanded="false">
                    Opciones
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu" role="menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(68px, 38px, 0px);">

                    <a class="dropdown-item" href="#">Action</a>



                {% if request.user.usuario == usuario.usuario %}

                {% else %}
                    <a role="button" class="dropdown-item" {% if usuario.is_active %} onclick="return confirm('¿Estás seguro de que deseas desactivar este Usuario?')"
                        {% else %} onclick="return confirm('¿Estás seguro de que quieres activar a este Usuario?')"
                        {% endif %}
                           href="{% url 'usuario:estado_usuario' pk=usuario.id %}" class="on_off" style="color: #454545; text-decoration: none;">
                            {% if usuario.is_active == True %}
                                <i class="fa fa-toggle-off"></i> Desactivar
                            {% else %}
                                <i class="fa fa-toggle-on"></i> Activa
                            {% endif %}
                    </a>

                    {%  if usuario.is_active %}
                        <a class="dropdown-item" onclick="return abrir_modal('{% url 'usuario:desactivar_usuario' usuario.id %}')" data-toggle="tooltip" data-placement="left" title="Desactivar"><i class="glyphicon glyphicon-eye-close"></i> Desactivar</a>
                    {% else %}
                        <a class="dropdown-item" onclick="return abrir_modal('{% url 'usuario:activar_usuario' usuario.id %}')" data-toggle="tooltip" data-placement="left" title="Activar"><i class="glyphicon glyphicon-eye-open"></i> Activar</a>
                    {% endif %}
                {% endif %}


                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Separated link</a>
                </div>
            </div>

        </td>
    </tr>
{% endfor %}